# Generated by Django 2.1 on 2020-01-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=256, verbose_name='Company name')),
                ('company_domain', models.CharField(max_length=256, verbose_name='Company Domain')),
                ('email_from', models.EmailField(blank=True, max_length=256, null=True, verbose_name='Email From')),
                ('email_to', models.EmailField(blank=True, max_length=256, null=True, verbose_name='Email To')),
                ('promotion_heading', models.CharField(max_length=256, verbose_name='Promotion Subject')),
                ('promotion_url', models.URLField(blank=True, null=True)),
                ('promotion_type', models.CharField(max_length=100, verbose_name='Role')),
                ('content', models.TextField()),
                ('promotion_snap', models.URLField()),
                ('medium', models.CharField(choices=[('fb', 'Facebook'), ('email', 'Email')], default='fb', max_length=64, verbose_name='Medium')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
