# Generated by Django 2.1 on 2020-02-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_mailgun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailgun',
            name='_from',
        ),
        migrations.AddField(
            model_name='mailgun',
            name='capital_from',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mailgun',
            name='content_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mailgun',
            name='date_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mailgun',
            name='dkim_signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mailgun',
            name='domain',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mailgun',
            name='from_from',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mailgun',
            name='message_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mailgun',
            name='message_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mailgun',
            name='mime_version',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mailgun',
            name='received_received',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mailgun',
            name='subject_subject',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mailgun',
            name='to_to',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mailgun',
            name='x_envelope_from',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mailgun',
            name='x_gm_message_state',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mailgun',
            name='x_google_dkim_signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mailgun',
            name='x_google_smtp_source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mailgun',
            name='x_mailgun_incoming',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mailgun',
            name='x_received',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mailgun',
            name='recipient',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mailgun',
            name='sender',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mailgun',
            name='subject',
            field=models.TextField(blank=True, null=True),
        ),
    ]
