# Generated by Django 2.1 on 2020-02-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_auto_20200203_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailgun',
            name='desktop_shot',
            field=models.ImageField(blank=True, null=True, upload_to='desktop'),
        ),
    ]
