# Generated by Django 2.1 on 2020-02-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_mailgun_desktop_shot'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailgun',
            name='mobile_shot',
            field=models.ImageField(blank=True, null=True, upload_to='desktop'),
        ),
    ]
